# Generated by Django 4.2.6 on 2023-10-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fashion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=20)),
                ('Price', models.CharField(max_length=5)),
                ('item_img', models.FileField(default=None, null=True, upload_to='homepage')),
            ],
        ),
    ]
