# Generated by Django 4.2.6 on 2023-10-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=20)),
                ('Price', models.CharField(max_length=5)),
                ('item_img', models.FileField(default=None, null=True, upload_to='homepage')),
            ],
        ),
    ]
